# The Docker Config version. Do not change.
version: "3.1"
services:
  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - "./frontend:/app"
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build: ./api-server
    container_name: server
    volumes:
      - "./api-server:/app"
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: "localhost"
      DB_CONNECTION_STRING: postgres://postgres:docker@db:5432/assessment_database
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: assessment_database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s
    volumes:
      - data-store:/var/lib/postgresql/data

volumes:
  data-store: